<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="2" passed="0">
  <reporter-output>
    <line>
      <![CDATA[Click to see Screenshot]]>
    </line>
    <line>
      <![CDATA[<a target="_blank" href=Tue_Jun_09_13_06_38_CEST_2020.jpg>Screenshot</a>]]>
    </line>
    <line>
      <![CDATA[<br>]]>
    </line>
    <line>
      <![CDATA[<br>]]>
    </line>
    <line>
      <![CDATA[<a target="_blank" href=Tue_Jun_09_13_06_38_CEST_2020.jpg><img src=Tue_Jun_09_13_06_38_CEST_2020.jpg widht=200 height=200></a>]]>
    </line>
    <line>
      <![CDATA[Click to see Screenshot]]>
    </line>
    <line>
      <![CDATA[<a target="_blank" href=Tue_Jun_09_13_06_48_CEST_2020.jpg>Screenshot</a>]]>
    </line>
    <line>
      <![CDATA[<br>]]>
    </line>
    <line>
      <![CDATA[<br>]]>
    </line>
    <line>
      <![CDATA[<a target="_blank" href=Tue_Jun_09_13_06_48_CEST_2020.jpg><img src=Tue_Jun_09_13_06_48_CEST_2020.jpg widht=200 height=200></a>]]>
    </line>
  </reporter-output>
  <suite name="Page Object Model" duration-ms="16430" started-at="2020-06-09T13:06:31 MESZ" finished-at="2020-06-09T13:06:48 MESZ">
    <groups>
    </groups>
    <test name="Login Test" duration-ms="16430" started-at="2020-06-09T13:06:31 MESZ" finished-at="2020-06-09T13:06:48 MESZ">
      <class name="com.w2a.testcases.LoginTest">
        <test-method status="FAIL" signature="loginTest(java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.w2a.testcases.LoginTest@25e2ab5a]" name="loginTest" duration-ms="4606" started-at="2020-06-09T13:06:31 MESZ" data-provider="dp" finished-at="2020-06-09T13:06:36 MESZ">
          <params>
            <param index="0">
              <value>
                <![CDATA[test.automatisierer@gmail.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[Selenium@123]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[Y]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Login test failed]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Login test failed
at org.testng.Assert.fail(Assert.java:97)
at com.w2a.testcases.LoginTest.loginTest(LoginTest.java:18)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:658)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:792)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1103)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:140)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:122)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:589)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:398)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:392)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:354)
at org.testng.SuiteRunner.run(SuiteRunner.java:302)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1145)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1067)
at org.testng.TestNG.runSuites(TestNG.java:997)
at org.testng.TestNG.run(TestNG.java:965)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:295)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:90)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Click to see Screenshot]]>
            </line>
            <line>
              <![CDATA[<a target="_blank" href=Tue_Jun_09_13_06_38_CEST_2020.jpg>Screenshot</a>]]>
            </line>
            <line>
              <![CDATA[<br>]]>
            </line>
            <line>
              <![CDATA[<br>]]>
            </line>
            <line>
              <![CDATA[<a target="_blank" href=Tue_Jun_09_13_06_38_CEST_2020.jpg><img src=Tue_Jun_09_13_06_38_CEST_2020.jpg widht=200 height=200></a>]]>
            </line>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.w2a.testcases.LoginTest@25e2ab5a]" name="tearDown" is-config="true" duration-ms="2" started-at="2020-06-09T13:06:48 MESZ" finished-at="2020-06-09T13:06:48 MESZ">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.w2a.testcases.LoginTest -->
      <class name="com.w2a.testcases.CreateAccountTest">
        <test-method status="FAIL" signature="createAccountTest(java.lang.String)[pri:0, instance:com.w2a.testcases.CreateAccountTest@35e5d0e5]" name="createAccountTest" duration-ms="9720" started-at="2020-06-09T13:06:38 MESZ" data-provider="dp" finished-at="2020-06-09T13:06:47 MESZ">
          <params>
            <param index="0">
              <value>
                <![CDATA[Raman]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Create account test failed]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Create account test failed
at org.testng.Assert.fail(Assert.java:97)
at com.w2a.testcases.CreateAccountTest.createAccountTest(CreateAccountTest.java:21)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:658)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:792)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1103)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:140)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:122)
at org.testng.TestRunner.privateRun(TestRunner.java:739)
at org.testng.TestRunner.run(TestRunner.java:589)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:398)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:392)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:354)
at org.testng.SuiteRunner.run(SuiteRunner.java:302)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1145)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1067)
at org.testng.TestNG.runSuites(TestNG.java:997)
at org.testng.TestNG.run(TestNG.java:965)
at org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:295)
at org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
at org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:90)
at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Click to see Screenshot]]>
            </line>
            <line>
              <![CDATA[<a target="_blank" href=Tue_Jun_09_13_06_48_CEST_2020.jpg>Screenshot</a>]]>
            </line>
            <line>
              <![CDATA[<br>]]>
            </line>
            <line>
              <![CDATA[<br>]]>
            </line>
            <line>
              <![CDATA[<a target="_blank" href=Tue_Jun_09_13_06_48_CEST_2020.jpg><img src=Tue_Jun_09_13_06_48_CEST_2020.jpg widht=200 height=200></a>]]>
            </line>
          </reporter-output>
        </test-method> <!-- createAccountTest -->
      </class> <!-- com.w2a.testcases.CreateAccountTest -->
    </test> <!-- Login Test -->
  </suite> <!-- Page Object Model -->
</testng-results>
