<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="Login Test"
           tests="1"
           failures="1"
           errors="0"
           skipped="0"
           time="9,720">
  <properties />
            <testcase name="createAccountTest" time="9,720" classname="com.w2a.testcases.CreateAccountTest">
                <failure type="java.lang.AssertionError"
                  message="Create account test failed"
              >
<![CDATA[java.lang.AssertionError: Create account test failed
  org.testng.Assert.fail(Assert.java:97)
  com.w2a.testcases.CreateAccountTest.createAccountTest(CreateAccountTest.java:21)
  sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
  sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
  sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
  java.lang.reflect.Method.invoke(Method.java:498)
  org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:131)
  org.testng.internal.Invoker.invokeMethod(Invoker.java:658)
  org.testng.internal.Invoker.invokeTestMethod(Invoker.java:792)
  org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1103)
  org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:140)
  org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:122)
  org.testng.TestRunner.privateRun(TestRunner.java:739)
  org.testng.TestRunner.run(TestRunner.java:589)
  org.testng.SuiteRunner.runTest(SuiteRunner.java:398)
  org.testng.SuiteRunner.runSequentially(SuiteRunner.java:392)
  org.testng.SuiteRunner.privateRun(SuiteRunner.java:354)
  org.testng.SuiteRunner.run(SuiteRunner.java:302)
  org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
  org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
  org.testng.TestNG.runSuitesSequentially(TestNG.java:1145)
  org.testng.TestNG.runSuitesLocally(TestNG.java:1067)
  org.testng.TestNG.runSuites(TestNG.java:997)
  org.testng.TestNG.run(TestNG.java:965)
  org.apache.maven.surefire.testng.TestNGExecutor.run(TestNGExecutor.java:295)
  org.apache.maven.surefire.testng.TestNGXmlTestSuite.execute(TestNGXmlTestSuite.java:84)
  org.apache.maven.surefire.testng.TestNGProvider.invoke(TestNGProvider.java:90)
  org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:203)
  org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:155)
  org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:103)
]]>
      </failure>

          </testcase>
  
  
  
</testsuite>
